project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "Machine Learning Fundamentals"
            file: content/01_journal/Machine_Learning_Fundamentals.qmd
          - text: "Regression"
            file: content/01_journal/Regression.qmd
          - text: "AutoML"
            file: content/01_journal/AutoML.qmd
          - text: "AutoML Part 2 and Performance Measures"
            file: content/01_journal/AutoML2PerfMeas.qmd
          - text: "LIME"
            file: content/01_journal/LIME.qmd
          - text: "Deep Learning"
            file: content/01_journal/DeepLearning.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto